package com.example.gamerag.service;
// 调用Milvus做找回
import com.example.gamerag.config.RagProperties;
import com.example.gamerag.exception.RagException;
import com.example.gamerag.model.RecallChannel;
import com.example.gamerag.model.RetrievalPlan;
import com.example.gamerag.model.SearchHit;
import com.example.gamerag.util.TextUtils;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

import java.time.Duration;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
public class MilvusRetrievalService {
    private static final Logger log = LoggerFactory.getLogger(MilvusRetrievalService.class);

    private final RagProperties properties;
    private final BgeEmbeddingClient embeddingClient;
    private final WebClient webClient;
    private final ObjectMapper objectMapper;

    public MilvusRetrievalService(RagProperties properties,
                                  BgeEmbeddingClient embeddingClient,
                                  WebClient.Builder builder,
                                  ObjectMapper objectMapper) {
        this.properties = properties;
        this.embeddingClient = embeddingClient;
        this.objectMapper = objectMapper;
        this.webClient = builder.clone()
                .baseUrl(properties.getMilvus().getEndpoint())
                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                .build();
    }

    public List<List<SearchHit>> recall(RetrievalPlan plan, List<String> keywords) {
        List<List<SearchHit>> rankedLists = new ArrayList<>();
        for (String query : plan.getSearchQueries()) {
            if (query == null || query.isBlank()) continue;
            if (plan.isDenseVector()) {
                rankedLists.add(denseSearch(query, plan.getFilterExpression()));
            }
            if (plan.isSparseBm25()) {
                rankedLists.add(sparseSearch(query, plan.getFilterExpression()));
            }
        }
        if (plan.isKeywordQuery()) {
            for (String keyword : TextUtils.distinctNonBlank(keywords, 8)) {
                rankedLists.add(keywordQuery(keyword, plan.getFilterExpression()));
            }
        }
        return rankedLists;
    }

    private List<SearchHit> denseSearch(String query, String filter) {
        try {
            List<Float> vector = embeddingClient.embed(query);
            Map<String, Object> body = baseSearchBody(properties.getMilvus().getDenseVectorField(), properties.getMilvus().getDenseTopK(), filter);
            body.put("data", List.of(vector));
            return postSearch(body, RecallChannel.DENSE_VECTOR);
        } catch (Exception e) {
            log.warn("dense vector search by BGE-M3 failed for query='{}': {}", query, e.getMessage());
            return List.of();
        }
    }

    private List<SearchHit> sparseSearch(String query, String filter) {
        try {
            if (properties.getMilvus().getSparseVectorField() == null || properties.getMilvus().getSparseVectorField().isBlank()) {
                return List.of();
            }
            Map<String, Object> body = baseSearchBody(properties.getMilvus().getSparseVectorField(), properties.getMilvus().getSparseTopK(), filter);
            // Sparse BM25 search usually does not need IVF/HNSW ANN parameters.
            body.remove("searchParams");
            // Milvus BM25 sparse field can accept the raw text query when the sparse vector field is generated by a BM25 function.
            body.put("data", List.of(query));
            return postSearch(body, RecallChannel.SPARSE_BM25);
        } catch (Exception e) {
            log.warn("sparse BM25 search failed for query='{}': {}", query, e.getMessage());
            return List.of();
        }
    }

    private List<SearchHit> keywordQuery(String keyword, String baseFilter) {
        try {
            String keywordFilter = properties.getMilvus().getKeywordFilterTemplate()
                    .replace("{textField}", properties.getMilvus().getTextField())
                    .replace("{keyword}", TextUtils.escapeMilvusString(keyword));
            String filter = combineFilter(baseFilter, keywordFilter);
            Map<String, Object> body = new LinkedHashMap<>();
            putDb(body);
            body.put("collectionName", properties.getMilvus().getCollection());
            body.put("filter", filter);
            body.put("limit", properties.getMilvus().getKeywordTopK());
            body.put("outputFields", properties.getMilvus().getOutputFields());
            return postQuery(body, RecallChannel.KEYWORD_QUERY);
        } catch (Exception e) {
            log.warn("keyword query failed for keyword='{}': {}", keyword, e.getMessage());
            return List.of();
        }
    }

    private Map<String, Object> baseSearchBody(String annsField, int limit, String filter) {
        Map<String, Object> body = new LinkedHashMap<>();
        putDb(body);
        body.put("collectionName", properties.getMilvus().getCollection());
        body.put("annsField", annsField);
        body.put("limit", limit);
        body.put("outputFields", properties.getMilvus().getOutputFields());
        if (filter != null && !filter.isBlank()) {
            body.put("filter", filter);
        }
        Map<String, Object> params = new LinkedHashMap<>();
        params.put("params", Map.of("nprobe", 10));
        body.put("searchParams", params);
        body.put("consistencyLevel", properties.getMilvus().getConsistencyLevel());
        return body;
    }

    private void putDb(Map<String, Object> body) {
        String db = properties.getMilvus().getDatabase();
        if (db != null && !db.isBlank() && !"default".equalsIgnoreCase(db)) {
            body.put("dbName", db);
        }
    }

    private List<SearchHit> postSearch(Map<String, Object> body, RecallChannel channel) {
        JsonNode root = postJson("/v2/vectordb/entities/search", body);
        return parseHits(root, channel);
    }

    private List<SearchHit> postQuery(Map<String, Object> body, RecallChannel channel) {
        JsonNode root = postJson("/v2/vectordb/entities/query", body);
        return parseHits(root, channel);
    }

    private JsonNode postJson(String path, Map<String, Object> body) {
        try {
            String response = webClient.post()
                    .uri(path)
                    .header(HttpHeaders.AUTHORIZATION, "Bearer " + properties.getMilvus().getToken())
                    .bodyValue(body)
                    .retrieve()
                    .onStatus(status -> status.is4xxClientError() || status.is5xxServerError(), resp ->
                            resp.bodyToMono(String.class).defaultIfEmpty("")
                                    .flatMap(err -> Mono.error(new RagException("Milvus REST 调用失败: HTTP " + resp.statusCode() + " " + err))))
                    .bodyToMono(String.class)
                    .block(Duration.ofSeconds(30));
            return objectMapper.readTree(response);
        } catch (RagException e) {
            throw e;
        } catch (Exception e) {
            throw new RagException("Milvus REST 调用异常: " + e.getMessage(), e);
        }
    }

    private List<SearchHit> parseHits(JsonNode root, RecallChannel channel) {
        List<SearchHit> hits = new ArrayList<>();
        JsonNode data = root.path("data");
        if (!data.isArray()) {
            return hits;
        }
        int[] rank = new int[]{1};
        for (JsonNode node : data) {
            if (node.isArray()) {
                for (JsonNode item : node) {
                    parseOneHit(item, channel, rank[0]++).ifPresent(hits::add);
                }
            } else {
                parseOneHit(node, channel, rank[0]++).ifPresent(hits::add);
            }
        }
        return hits;
    }

    private java.util.Optional<SearchHit> parseOneHit(JsonNode node, RecallChannel channel, int rank) {
        JsonNode entity = node.path("entity").isMissingNode() ? node : node.path("entity");
        String id = readText(entity, properties.getMilvus().getPrimaryKeyField());
        if (id == null || id.isBlank()) {
            id = readText(node, properties.getMilvus().getPrimaryKeyField());
        }
        if (id == null || id.isBlank()) {
            id = readText(node, "id");
        }
        String content = readText(entity, properties.getMilvus().getTextField());
        if (id == null || id.isBlank() || content == null || content.isBlank()) {
            return java.util.Optional.empty();
        }
        SearchHit hit = new SearchHit();
        hit.setId(id);
        hit.setTitle(readText(entity, properties.getMilvus().getTitleField()));
        hit.setContent(content);
        hit.setSource(readText(entity, properties.getMilvus().getSourceField()));
        hit.setUrl(readText(entity, properties.getMilvus().getUrlField()));
        hit.setScore(readScore(node, rank));
        hit.setRank(rank);
        hit.setChannel(channel);
        Map<String, Object> meta = new LinkedHashMap<>();
        for (String field : properties.getMilvus().getOutputFields()) {
            JsonNode val = entity.path(field);
            if (!val.isMissingNode() && !val.isNull()) {
                meta.put(field, val.isValueNode() ? val.asText() : val.toString());
            }
        }
        hit.setMetadata(meta);
        return java.util.Optional.of(hit);
    }

    private String readText(JsonNode node, String field) {
        if (node == null || field == null || field.isBlank()) return null;
        JsonNode value = node.path(field);
        if (value.isMissingNode() || value.isNull()) return null;
        return value.isValueNode() ? value.asText() : value.toString();
    }

    private double readScore(JsonNode node, int rank) {
        if (node.has("score")) return node.path("score").asDouble();
        if (node.has("distance")) return node.path("distance").asDouble();
        return 1.0 / Math.max(1, rank);
    }

    private String combineFilter(String baseFilter, String extraFilter) {
        if (baseFilter == null || baseFilter.isBlank()) return extraFilter;
        if (extraFilter == null || extraFilter.isBlank()) return baseFilter;
        return "(" + baseFilter + ") && (" + extraFilter + ")";
    }
}
